# Generated by Django 6.1 on 2026-08-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address_snapshot',
            field=models.JSONField(blank=True, help_text='Historical snapshot of shipping address at order placement.', null=True),
        ),
    ]
