# Generated by Django 6.1 on 2026-08-18 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PRODUCT_VIEW', 'Product View'), ('PRODUCT_SEARCH', 'Product Search'), ('ADD_TO_CART', 'Add to Cart'), ('REMOVE_FROM_CART', 'Remove from Cart'), ('ADD_TO_WISHLIST', 'Add to Wishlist'), ('REMOVE_FROM_WISHLIST', 'Remove from Wishlist'), ('CHECKOUT_STARTED', 'Checkout Started'), ('PURCHASE', 'Purchase'), ('PRODUCT_REVIEWED', 'Product Reviewed')], db_index=True, max_length=30)),
                ('search_query', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User activities',
            },
        ),
    ]
